FILE = task_4
FLAG_1 = -o
FLAG_2 = -Wall
FLAG_3 = -Wshadow
FLAG_4 = -Wextra
FLAG_5 = -pedantic
FLAG_6 = -g
EXEC_FILE = task4

PHONY: task4 all clean

all: $(FILE).c

		$(CC) $(FILE).c $(FLAG_1) $(EXEC_FILE) $(FLAG_2) $(FLAG_3) $(FLAG_4) $(FLAG_5) $(FLAG_6)

task_4: 

		./$(EXEC_FILE) Hello!

clean:

		rm -rf ./$(EXEC_FILE)
