
FLAG_1 = -o
FLAG_2 = -Wall
FILE_1 =  eltex_ex_2_ex_4
CC = gcc
EXEC_FILE_1 = snake

all: $(FILE_1).c

	$(CC) $(FILE_1).c $(FLAG_1) $(EXEC_FILE_1) $(FLAG_2)

test_snake:

	./$(EXEC_FILE_1)

clean:

	rm ./$(EXEC_FILE_1)




