
FLAG_1 = -o
FLAG_2 = -Wall
FILE_1 = hello_world
CC = gcc
EXEC = hello_world

all: $(FILE_1).c

	 $(CC) $(FILE_1).c $(FLAG_1) $(EXEC) $(FLAG_2)

test_hello_world:

	./$(EXEC)

clean:
	rm ./$(EXEC)




