FILE = main
FILE_2 = wait
FILE_3 = string_parser
FILE_4 = my_bash
FLAG_1 = -o
FLAG_2 = -Wall
FLAG_3 = -Wshadow
FLAG_4 = -Wextra
FLAG_5 = -pedantic
FLAG_6 = -g
EXEC_FILE = task5

PHONY: task5 all clean

all: $(FILE).c $(FILE_2).c $(FILE_3).c $(FILE_4).c

		$(CC) $(FILE).c $(FILE_2).c $(FILE_3).c $(FILE_4).c  $(FLAG_1) $(EXEC_FILE) $(FLAG_2) $(FLAG_3) $(FLAG_4) $(FLAG_5) $(FLAG_6)

task_5: 

		./$(EXEC_FILE)

clean:
		rm -rf ./$(EXEC_FILE)
