CC = gcc
FILE = customer_store
FLAG_1 = -o
FLAG_2 = -Wall
FLAG_3 = -pthread
FLAG_4 = -g
EXEC_FILE = customer_store

.PHONY: customer_store all clean

all: $(FILE).c

		$(CC) $(FILE).c $(FLAG_1) $(EXEC_FILE) $(FLAG_2) $(FLAG_3) $(FLAG_4)

customer_store:

		./$(EXEC_FILE)
clean:

		rm -rf ./$(EXEC_FILE)




