FLAG_1 = -o
FLAG_2 = -Wall
FILE_1 = eltex_ex_2
CC = gcc
EXEC_FILE_1 = matrix_display

all: $(FILE_1).c

	 $(CC) $(FILE_1).c $(FLAG_1) $(EXEC_FILE_1) $(FLAG_2)

test_matrix_display:

	./$(EXEC_FILE_1)

clean:
	rm ./$(EXEC_FILE_1)

