CC = gcc
FILE = main
FLAG_1 = -o
FLAG_2 = -Wall
EXEC_FILE = fork_2

.PHONY: fork_2 all clean

all: $(FILE).c

	$(CC) $(FILE).c $(FLAG_1) $(EXEC_FILE) $(FLAG_2)

fork_2:

	./$(EXEC_FILE)

clean:

	rm -rf ./$(EXEC_FILE)



