FLAG_1 = -o
FLAG_2 = -Wall
FLAG_3 = -pedantic
FILE_1 = eltex_lab_4_ex_2
CC = gcc
EXEC_FILE_1 = pad_no_pad

all: $(FILE_1).c

	$(CC) $(FILE_1).c $(FLAG_1) $(EXEC_FILE_1) $(FLAG_3) $(FLAG_2)

test_pad_no_pad:

	./$(EXEC_FILE_1)
clean:

	rm ./$(EXEC_FILE_1)

