CC = gcc
FILE = bash
FLAG_1 = -o
FLAG_2 = -Wall
EXEC_FILE = bash

.PHONY: bash all clean

all: $(FILE).c

	$(CC) $(FILE).c $(FLAG_1) $(EXEC_FILE) $(FLAG_2)

bash:

	./$(EXEC_FILE)

clean:

	rm -rf ./$(EXEC_FILE)





