FILE = task_3
FLAG_1 = -o
FLAG_2 = -Wall
FLAG_3 = -Wshadow
FLAG_4 = -Wextra
FLAG_5 = -pedantic
FLAG_6 = -g
EXEC_FILE = task3

PHONY: task3 all clean 

all: $(FILE).c

		$(CC) $(FILE).c $(FLAG_1) $(EXEC_FILE) $(FLAG_2) $(FLAG_3) $(FLAG_4) $(FLAG_5) $(FLAG_6)

task_3: 

		./$(EXEC_FILE) ls -la grep task nl

clean:

		rm -rf ./$(EXEC_FILE)
